### ISSUE TITLE
Unexpected build failures caused by v1.1.6

### ISSUE THREAD

**Issue by coxlinton** [npm/are-we-there-yet#112]
# What / Why
v1.1.6 dropped support for Node.js < 10
All projects that directly _or indirectly_ (e.g. through npmlog) have a dependency declared on some version of v1.1,  e.g. ```"are-we-there-yet": "~1.1.2"``` will pick up the new version 1.1.6 and will thus break if they're using Node < 10. 

Was this intended? My normal expectation of semantic versioning is that a breaking change like modifying supported Node versions would be a major version change i.e. 2.0.0, as per the semantic versioning guidelines https://semver.org/:

>Given a version number MAJOR.MINOR.PATCH, increment the
> -  MAJOR version when you make incompatible API changes,
> -  MINOR version when you add functionality in a backwards compatible manner, and
> -  PATCH version when you make backwards compatible bug fixes.

As it stands, it seems there may be many projects (such as my own :) using Node < 10 that will suddenly be experiencing unexpected build failures due to the automatic version upgrade of a transitive dependency on are-we-there-yet.

## Where
Any project with a transitive dependency on v1.1

## Workaround
If using yarn or npm-force-resolutions, you can add a resolutions block to your package.json:
```
  "resolutions": {
    "are-we-there-yet": "<=1.1.5"
  },
```
However, this isn't a solution if you're a library creator with a transitive dependency to are-we-there-yet; resolutions are only processed on top-level package.json files.

npm shrinkwrap may also be an option (only if you're not using yarn).

**Comment by max-petrovich** [comment]
node-saas@3.13.1 is broken on this version!

**Comment by wraithgar** [comment]
Sorry about that. Looks like there was some unpublished stuff in the repo that got sent out w/ this week's new "get things on github actions" push.

`v1.1.7` has been published based off of the `v1.1.5` code, `v1.1.6` has been deprecated.  `v2.0.0` has been published based off of the `v1.1.6` code.
