### ISSUE TITLE
[QUESTION] Changes between 1.1.6 -> 1.1.7 -> 2.0.0 not obvious

### ISSUE THREAD

**Issue by fritzy** [npm/are-we-there-yet#115]
# What / Why
There appears to be a 1.1.7 that has no differences from 1.1.6 other than the versions. This showed up when cutting a release, and it's confusing. What was the change and what were the commits?

## Who
  * @wraithgar

**Comment by isaacs** [comment]
>       "deprecated": "This version accidentally shipped with code dropping support for node <=10. Please update to v1.1.7 or >2"

It _shouldn't_ try to install it or show it in `npm outdated`, since it's deprecated.

**Comment by wraithgar** [comment]
`v1.1.7` was a republish of `v1.1.5` with a version bump to bring it above `v1.1.6` https://github.com/npm/are-we-there-yet/commits/v1.1.7

`v1.1.6` was a publish that contained commits from as far back as May 2108 that were in `main` but not published https://github.com/npm/are-we-there-yet/commits/v1.1.6

Github's UI is broken for the comparison of those two tags for some reason.  In a terminal you get the real story

```sh
~/D/n/are-we-there-yet (main|✔) $ git diff v1.1.6 v1.1.7 --stat
 .eslintrc.js                               |    12 -
 .github/settings.yml                       |     2 -
 .github/workflows/ci.yml                   |    52 -
 .gitignore                                 |    21 +-
 .travis.yml                                |     6 +
 LICENSE                                    |     5 +
 LICENSE.md                                 |    18 -
 README.md                                  |    19 +-
 lib/index.js => index.js                   |     0
 package-lock.json                          | 13286 +++++++++++++++++++++++++++++++++++-----------------------------------------------------------------------------
 package.json                               |    52 +-
 test/lib/tracker.js                        |    57 -
 test/lib/trackergroup.js                   |   108 -
 test/tracker.js                            |    57 +
 test/trackergroup.js                       |   108 +
 test/{lib => }/trackerstream.js            |    22 +-
 lib/tracker-base.js => tracker-base.js     |     0
 lib/tracker-group.js => tracker-group.js   |    19 +-
 lib/tracker-stream.js => tracker-stream.js |     0
 lib/tracker.js => tracker.js               |     4 +-
 20 files changed, 4385 insertions(+), 9463 deletions(-)
```
